import { ThemeId } from '../types';

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  background: string;
  cardBg: string;
  textColor: string;
  accent: string;
  headerFont: string;
  bodyFont: string;
}

export const THEMES: Record<ThemeId, ThemeConfig> = {
  party: {
    id: 'party',
    name: 'Party Time',
    background: 'bg-gradient-to-br from-purple-500 via-pink-500 to-red-500',
    cardBg: 'bg-white/90 backdrop-blur-sm',
    textColor: 'text-slate-800',
    accent: 'text-pink-500',
    headerFont: 'font-serif font-black tracking-tight',
    bodyFont: 'font-sans',
  },
  elegant: {
    id: 'elegant',
    name: 'Elegant Gold',
    background: 'bg-slate-900',
    cardBg: 'bg-slate-800/90 backdrop-blur-sm border border-slate-700',
    textColor: 'text-slate-100',
    accent: 'text-amber-400',
    headerFont: 'font-serif italic',
    bodyFont: 'font-sans font-light',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Breeze',
    background: 'bg-gradient-to-tr from-cyan-400 to-blue-500',
    cardBg: 'bg-white/90 backdrop-blur-sm',
    textColor: 'text-cyan-950',
    accent: 'text-cyan-600',
    headerFont: 'font-serif',
    bodyFont: 'font-sans',
  },
  sunset: {
    id: 'sunset',
    name: 'Warm Sunset',
    background: 'bg-gradient-to-br from-orange-400 via-rose-400 to-purple-500',
    cardBg: 'bg-white/95 backdrop-blur-md',
    textColor: 'text-orange-950',
    accent: 'text-rose-500',
    headerFont: 'font-sans font-bold',
    bodyFont: 'font-serif',
  },
  nature: {
    id: 'nature',
    name: 'Fresh Nature',
    background: 'bg-gradient-to-bl from-green-300 to-emerald-600',
    cardBg: 'bg-green-50/90 backdrop-blur-md',
    textColor: 'text-green-950',
    accent: 'text-emerald-600',
    headerFont: 'font-serif',
    bodyFont: 'font-sans',
  },
  cosmos: {
    id: 'cosmos',
    name: 'Cosmos',
    background: 'bg-gradient-to-r from-indigo-900 via-purple-900 to-black',
    cardBg: 'bg-white/10 backdrop-blur-xl border border-white/20',
    textColor: 'text-indigo-100',
    accent: 'text-indigo-300',
    headerFont: 'font-serif font-light tracking-wide',
    bodyFont: 'font-sans font-light text-slate-300',
  },
  cherryBlossom: {
    id: 'cherryBlossom',
    name: 'Cherry Blossom',
    background: 'bg-gradient-to-b from-pink-200 to-rose-100',
    cardBg: 'bg-white/80 backdrop-blur border border-pink-100',
    textColor: 'text-rose-900',
    accent: 'text-pink-500',
    headerFont: 'font-serif text-pink-600',
    bodyFont: 'font-sans',
  },
  neon: {
    id: 'neon',
    name: 'Neon Cyber',
    background: 'bg-slate-950',
    cardBg: 'bg-slate-900/80 border border-fuchsia-500/50 shadow-[0_0_15px_rgba(217,70,239,0.5)]',
    textColor: 'text-slate-200',
    accent: 'text-fuchsia-400',
    headerFont: 'font-mono font-bold tracking-tight',
    bodyFont: 'font-mono text-sm',
  },
  minimalist: {
    id: 'minimalist',
    name: 'Minimalist',
    background: 'bg-slate-50',
    cardBg: 'bg-white border border-slate-200 shadow-sm',
    textColor: 'text-slate-800',
    accent: 'text-slate-900',
    headerFont: 'font-sans font-medium tracking-tight',
    bodyFont: 'font-sans text-slate-600 font-light',
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage Paper',
    background: 'bg-amber-100/50',
    cardBg: 'bg-[#f4ebd0] shadow-md border border-[#e6d5aa]',
    textColor: 'text-[#4a3f35]',
    accent: 'text-[#8b5a2b]',
    headerFont: 'font-serif italic tracking-wide',
    bodyFont: 'font-serif',
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora Borealis',
    background: 'bg-gradient-to-br from-green-400 via-teal-500 to-indigo-600',
    cardBg: 'bg-slate-900/60 backdrop-blur-lg border border-teal-500/30',
    textColor: 'text-teal-50',
    accent: 'text-teal-300',
    headerFont: 'font-sans font-light',
    bodyFont: 'font-sans',
  },
  royal: {
    id: 'royal',
    name: 'Royal Velvet',
    background: 'bg-gradient-to-br from-red-900 to-rose-950',
    cardBg: 'bg-white/5 backdrop-blur-md border border-red-800/50',
    textColor: 'text-red-50',
    accent: 'text-amber-400',
    headerFont: 'font-serif font-bold',
    bodyFont: 'font-serif text-rose-200 text-lg',
  },
  pastel: {
    id: 'pastel',
    name: 'Pastel Dream',
    background: 'bg-gradient-to-tr from-pink-300 via-purple-300 to-indigo-400',
    cardBg: 'bg-white/80 backdrop-blur-sm',
    textColor: 'text-slate-700',
    accent: 'text-purple-600',
    headerFont: 'font-sans font-black',
    bodyFont: 'font-sans font-medium',
  },
  fire: {
    id: 'fire',
    name: 'Fire & Ember',
    background: 'bg-gradient-to-t from-red-600 via-orange-500 to-yellow-400',
    cardBg: 'bg-black/80 backdrop-blur-sm',
    textColor: 'text-orange-50',
    accent: 'text-yellow-400',
    headerFont: 'font-sans font-black uppercase tracking-widest',
    bodyFont: 'font-sans',
  },
  ice: {
    id: 'ice',
    name: 'Glacier Ice',
    background: 'bg-gradient-to-b from-sky-400 to-cyan-200',
    cardBg: 'bg-white/60 backdrop-blur-xl border border-white',
    textColor: 'text-sky-950',
    accent: 'text-sky-600',
    headerFont: 'font-sans font-bold tracking-tight',
    bodyFont: 'font-sans font-medium',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender Field',
    background: 'bg-gradient-to-tr from-violet-200 to-fuchsia-200',
    cardBg: 'bg-white/70 backdrop-blur-md',
    textColor: 'text-violet-900',
    accent: 'text-violet-600',
    headerFont: 'font-serif italic',
    bodyFont: 'font-sans text-violet-800',
  },
  forest: {
    id: 'forest',
    name: 'Deep Forest',
    background: 'bg-gradient-to-br from-green-900 to-emerald-950',
    cardBg: 'bg-emerald-950/80 backdrop-blur-sm border border-emerald-800',
    textColor: 'text-emerald-100',
    accent: 'text-emerald-400',
    headerFont: 'font-serif tracking-widest',
    bodyFont: 'font-sans font-light',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight Bloom',
    background: 'bg-slate-950',
    cardBg: 'bg-slate-900/90 border border-slate-800',
    textColor: 'text-slate-300',
    accent: 'text-rose-500',
    headerFont: 'font-serif italic text-rose-400',
    bodyFont: 'font-sans font-light text-slate-400',
  },
  sunshine: {
    id: 'sunshine',
    name: 'Morning Sunshine',
    background: 'bg-gradient-to-br from-yellow-100 to-amber-300',
    cardBg: 'bg-white/80 backdrop-blur border border-yellow-200',
    textColor: 'text-amber-900',
    accent: 'text-orange-500',
    headerFont: 'font-sans font-black tracking-tight',
    bodyFont: 'font-sans font-medium',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome',
    background: 'bg-slate-200',
    cardBg: 'bg-black border border-slate-800 shadow-2xl',
    textColor: 'text-white',
    accent: 'text-slate-400',
    headerFont: 'font-sans font-bold uppercase tracking-widest',
    bodyFont: 'font-sans font-light',
  },
  candy: {
    id: 'candy',
    name: 'Cotton Candy',
    background: 'bg-gradient-to-r from-pink-300 to-cyan-300',
    cardBg: 'bg-white/90 backdrop-blur-sm rounded-3xl',
    textColor: 'text-pink-900',
    accent: 'text-cyan-500',
    headerFont: 'font-sans font-black text-pink-600',
    bodyFont: 'font-sans font-semibold',
  },
  coffee: {
    id: 'coffee',
    name: 'Coffee Roast',
    background: 'bg-[#cfbaa8]',
    cardBg: 'bg-[#5c4a3d] border border-[#4a3f35] rounded-sm',
    textColor: 'text-[#eaddcf]',
    accent: 'text-[#cfbaa8]',
    headerFont: 'font-serif font-bold',
    bodyFont: 'font-serif',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyber City',
    background: 'bg-gradient-to-br from-yellow-400 via-red-500 to-pink-600',
    cardBg: 'bg-black/95 border-l-4 border-yellow-400',
    textColor: 'text-cyan-400',
    accent: 'text-yellow-400',
    headerFont: 'font-mono font-black uppercase',
    bodyFont: 'font-mono text-pink-400 text-sm',
  },
  watercolor: {
    id: 'watercolor',
    name: 'Watercolor Canvas',
    background: 'bg-gradient-to-br from-blue-100 via-teal-100 to-emerald-100',
    cardBg: 'bg-white/60 backdrop-blur-xl border border-white/50 shadow-lg',
    textColor: 'text-slate-600',
    accent: 'text-teal-600',
    headerFont: 'font-serif italic opacity-80',
    bodyFont: 'font-sans font-medium opacity-90',
  },
  galaxy: {
    id: 'galaxy',
    name: 'Deep Galaxy',
    background: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-900 via-indigo-950 to-black',
    cardBg: 'bg-black/40 backdrop-blur-md border border-purple-500/30',
    textColor: 'text-indigo-100',
    accent: 'text-fuchsia-400',
    headerFont: 'font-sans font-light tracking-widest',
    bodyFont: 'font-sans font-light',
  },
  peaches: {
    id: 'peaches',
    name: 'Peaches & Cream',
    background: 'bg-gradient-to-tr from-orange-100 to-rose-200',
    cardBg: 'bg-white/90 shadow-xl border border-orange-100',
    textColor: 'text-rose-900',
    accent: 'text-orange-500',
    headerFont: 'font-serif font-bold',
    bodyFont: 'font-sans',
  },
  retro: {
    id: 'retro',
    name: '80s Retro',
    background: 'bg-gradient-to-b from-indigo-900 via-purple-700 to-pink-500',
    cardBg: 'bg-slate-900/80 border-t-4 border-pink-500 shadow-xl',
    textColor: 'text-cyan-300',
    accent: 'text-pink-500',
    headerFont: 'font-sans font-black italic tracking-tighter',
    bodyFont: 'font-mono text-yellow-400',
  },
  mint: {
    id: 'mint',
    name: 'Mint Chocolate',
    background: 'bg-[#a3e4d7]',
    cardBg: 'bg-[#3e2723] rounded-2xl shadow-lg',
    textColor: 'text-[#e0f2f1]',
    accent: 'text-[#1abc9c]',
    headerFont: 'font-serif font-bold',
    bodyFont: 'font-sans text-sm',
  },
  slate: {
    id: 'slate',
    name: 'Modern Slate',
    background: 'bg-slate-200',
    cardBg: 'bg-slate-100 border border-slate-300 shadow-lg rounded-none',
    textColor: 'text-slate-800',
    accent: 'text-slate-500',
    headerFont: 'font-sans font-semibold tracking-tight',
    bodyFont: 'font-sans font-light text-sm text-slate-600',
  },
  holographic: {
    id: 'holographic',
    name: 'Holographic',
    background: 'bg-[conic-gradient(at_top_right,_var(--tw-gradient-stops))] from-rose-400 via-fuchsia-500 to-indigo-500',
    cardBg: 'bg-white/20 backdrop-blur-2xl border border-white/50 shadow-2xl rounded-3xl',
    textColor: 'text-white text-shadow-sm',
    accent: 'text-indigo-100',
    headerFont: 'font-sans font-black tracking-tighter',
    bodyFont: 'font-sans font-medium',
  }
};
